/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.ICustomerAccess;
import co.unicauca.restaurant.client.domain.services.CustomerService;
import static co.unicauca.restaurant.client.infra.Messages.successMessage;
import co.unicauca.restaurant.commons.domain.Customer;

/**
 *
 * @author Libardo Pantoja, Julio Hurtado
 */
public class GUICustomer extends javax.swing.JFrame {

    /**
     * Creates new form GUICustomer
     */
    public GUICustomer() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustomerId = new javax.swing.JTextField();
        txtCustomerFirstName = new javax.swing.JTextField();
        lblCustomerId = new javax.swing.JLabel();
        lblCustomerFirstName = new javax.swing.JLabel();
        lblCustomerLastName = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        txtCustomerLastName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        lblCustomerPhoneNumber = new javax.swing.JLabel();
        lblCustomerEmail = new javax.swing.JLabel();
        txtCustomerPhoneNumber = new javax.swing.JTextField();
        txtCustomerEmail = new javax.swing.JTextField();
        txtCustomerGender = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        btnAddCustomer.setVisible(false);
        btnBack = new javax.swing.JButton();
        lblFindCustomerId = new javax.swing.JLabel();
        txtFindCustomerId = new javax.swing.JTextField();
        btnFindCustomer = new javax.swing.JButton();
        lblCustomerGender = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        lblCustomerId.setText("Id cliente: ");

        lblCustomerFirstName.setText("Nombres cliente:");

        lblCustomerLastName.setText("Apellidos cliente: ");

        lblCustomerAddress.setText("Direccion cliente:");

        lblCustomerPhoneNumber.setText("Numero de telefono cliente: ");

        lblCustomerEmail.setText("Correo electronico cliente:");

        btnAddCustomer.setText("Agregar");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFindCustomerId.setText("Digite id a buscar: ");

        btnFindCustomer.setText("Buscar");
        btnFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustomerActionPerformed(evt);
            }
        });

        lblCustomerGender.setText("*Sexo (M, F):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblFindCustomerId)
                .addGap(18, 18, 18)
                .addComponent(txtFindCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindCustomer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCustomerGender)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCustomerPhoneNumber)
                                .addComponent(txtCustomerLastName)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCustomerId)
                                .addComponent(lblCustomerLastName)
                                .addComponent(lblCustomerPhoneNumber))
                            .addComponent(txtCustomerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addComponent(lblCustomerFirstName)
                            .addComponent(lblCustomerAddress)
                            .addComponent(txtCustomerFirstName)
                            .addComponent(txtCustomerAddress)
                            .addComponent(lblCustomerEmail)
                            .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCustomerId)
                    .addComponent(txtFindCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindCustomer))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerId)
                    .addComponent(lblCustomerFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerLastName)
                    .addComponent(lblCustomerAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCustomerLastName)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerPhoneNumber)
                    .addComponent(lblCustomerEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCustomerGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnBack))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        ICustomerAccess service = Factory.getInstance().getCustomerService();
        // Inyecta la dependencia
        CustomerService customerService = new CustomerService(service);

        Customer customer = new Customer();
        customer.setId(txtCustomerId.getText());
        customer.setFirstName(txtCustomerFirstName.getText());
        customer.setLastName(txtCustomerLastName.getText());
        customer.setAddress(txtCustomerAddress.getText());
        customer.setEmail(txtCustomerEmail.getText());
        customer.setMobile(txtCustomerPhoneNumber.getText());
        customer.setGender(txtCustomerGender.getText());

        try {
            String response = customerService.createCustomer(customer);
            successMessage("Cliente "+ response + " agregado con éxito.", "Atención");
            clearData();
            txtFindCustomerId.setText("");
            btnAddCustomer.setVisible(false);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustomerActionPerformed
        String id = txtFindCustomerId.getText().trim();
        ICustomerAccess service = Factory.getInstance().getCustomerService();

        CustomerService customerService = new CustomerService(service);
        if (id.equals("")) {
            btnAddCustomer.setVisible(false);
            txtCustomerFirstName.requestFocus();
            return;
        }

        Customer customer;
        try {
            customer = customerService.findCustomer(id);
        } catch (Exception ex) {
            clearData();
            successMessage(ex.getMessage(), "Atención");
            txtCustomerId.setText(txtFindCustomerId.getText());
            btnAddCustomer.setVisible(true);
            return;
        }
        clearData();
        showData(customer);
    }//GEN-LAST:event_btnFindCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIMain ins = new GUIMain();
                ins.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void showData (Customer data) {
        txtCustomerId.setText(data.getId());
        txtCustomerFirstName.setText(data.getFirstName());
        txtCustomerLastName.setText(data.getLastName());
        txtCustomerAddress.setText(data.getAddress());
        txtCustomerPhoneNumber.setText(data.getMobile());
        txtCustomerEmail.setText(data.getEmail());
        txtCustomerGender.setText(data.getGender());
    }

    private void clearData(){
        // txtFindCustomerId.setText("");
        txtCustomerId.setText("");
        txtCustomerFirstName.setText("");
        txtCustomerLastName.setText("");
        txtCustomerAddress.setText("");
        txtCustomerPhoneNumber.setText("");
        txtCustomerEmail.setText("");
        txtCustomerGender.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerEmail;
    private javax.swing.JLabel lblCustomerFirstName;
    private javax.swing.JLabel lblCustomerGender;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerLastName;
    private javax.swing.JLabel lblCustomerPhoneNumber;
    private javax.swing.JLabel lblFindCustomerId;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerFirstName;
    private javax.swing.JTextField txtCustomerGender;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerLastName;
    private javax.swing.JTextField txtCustomerPhoneNumber;
    private javax.swing.JTextField txtFindCustomerId;
    // End of variables declaration//GEN-END:variables
}
