package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.IFoodAccess;
import co.unicauca.restaurant.client.domain.services.FoodService;
import static co.unicauca.restaurant.client.infra.Messages.successMessage;
import co.unicauca.restaurant.commons.domain.Food;

/**
 *
 * @author Libardo Pantoja, Julio Hurtado
 */
public class GUIFood extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIFood() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFindFoodId = new javax.swing.JTextField();
        btnBuscarFood = new javax.swing.JButton();
        txtFoodId = new javax.swing.JTextField();
        lblFoodId = new javax.swing.JLabel();
        txtFoodName = new javax.swing.JTextField();
        lblFoodName = new javax.swing.JLabel();
        txtFoodDescription = new javax.swing.JTextField();
        lblFoodDescription = new javax.swing.JLabel();
        btnAddFood = new javax.swing.JButton();
        btnAddFood.setVisible(false);
        btnBack = new javax.swing.JButton();
        lblFindFood = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        btnBuscarFood.setText("Buscar");
        btnBuscarFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFoodActionPerformed(evt);
            }
        });

        lblFoodId.setText("Id de la comida: ");

        lblFoodName.setText("Nombre de la comida: ");

        lblFoodDescription.setText("Descripcion de la comida: ");
        lblFoodDescription.setToolTipText("");

        btnAddFood.setText("Agregar");
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFindFood.setText("Digite id a buscar: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFoodId)
                            .addComponent(lblFoodName)
                            .addComponent(lblFoodDescription)
                            .addComponent(btnAddFood))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFoodDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtFoodName)
                                    .addComponent(txtFoodId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(btnBack))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFindFood)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindFoodId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnBuscarFood)))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindFoodId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFood)
                    .addComponent(lblFindFood))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoodId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodDescription))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFood)
                    .addComponent(btnBack))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFoodActionPerformed
        String id = txtFindFoodId.getText().trim();
        IFoodAccess service = Factory.getInstance().getFoodService();

        FoodService foodService = new FoodService(service);
        if (id.equals("")) {
            btnAddFood.setVisible(false);
            txtFoodName.requestFocus();
            return;
        }

        Food food;
        try {
            food = foodService.findFood(id);
        } catch (Exception ex) {
            clearData();
            successMessage(ex.getMessage(), "Atención");
            txtFoodId.setText(txtFindFoodId.getText());
            btnAddFood.setVisible(true);
            return;
        }
        clearData();
        showData(food);
    }//GEN-LAST:event_btnBuscarFoodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIMain ins = new GUIMain();
                ins.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        IFoodAccess service = Factory.getInstance().getFoodService();
        // Inyecta la dependencia
        FoodService foodService = new FoodService(service);

        Food food = new Food();
        food.setId(txtFoodId.getText());
        food.setName(txtFoodName.getText());
        food.setDescription(txtFoodDescription.getText());


        try {
            String response = foodService.createFood(food);
            successMessage("Comida "+ response + " agregado con éxito.", "Atención");
            clearData();
            txtFindFoodId.setText("");
            btnAddFood.setVisible(false);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btnAddFoodActionPerformed


    private void clearData() {

        //txtFindFoodId.setText("");
        txtFoodId.setText("");
        txtFoodName.setText("");
        txtFoodDescription.setText("");

    }   

    private void showData (Food data) {
        txtFoodId.setText(data.getId());
        txtFoodName.setText(data.getName());
        txtFoodDescription.setText(data.getDescription());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuscarFood;
    private javax.swing.JLabel lblFindFood;
    private javax.swing.JLabel lblFoodDescription;
    private javax.swing.JLabel lblFoodId;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JTextField txtFindFoodId;
    private javax.swing.JTextField txtFoodDescription;
    private javax.swing.JTextField txtFoodId;
    private javax.swing.JTextField txtFoodName;
    // End of variables declaration//GEN-END:variables
}
